name       : haskell-regex-pcre-builtin
version    : 0.94.4.8.8.35
release    : 1
source     :
    - https://hackage.haskell.org/package/regex-pcre-builtin-0.94.4.8.8.35/regex-pcre-builtin-0.94.4.8.8.35.tar.gz : 0bd1b695de953ba4b6e6e0de007021c346cb2a6c8e09356fbcd34f8a79d2ea78
license    : BSD-3-Clause
component  : programming.haskell
summary    : The PCRE backend to accompany regex-base
description: |
    The PCRE backend to accompany regex-base
builddeps  :
    - haskell-cabal-install
    - haskell-regex-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
