name       : haskell-regex-pcre-builtin
version    : 0.95.1.2.8.43
release    : 3
source     :
    - https://hackage.haskell.org/package/regex-pcre-builtin-0.95.1.2.8.43/regex-pcre-builtin-0.95.1.2.8.43.tar.gz : b4ae10ad53726249b064f880984ecba2a500ba27e47cb60b2e2af0f44643b6af
license    : BSD-3-Clause
component  : programming.haskell
summary    : The PCRE backend to accompany regex-base
description: |
    The PCRE backend to accompany regex-base
builddeps  :
    - haskell-cabal-install
    - haskell-regex-base-devel
rundeps    :
    - devel:
        - haskell-regex-base-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
